export const DND_ITEM = {
    TOP_NAV_ITEM: 'TOP_NAV_ITEM',
    MAIL_ACCOUNT_ITEM: 'MAIL_ACCOUNT_ITEM',
    MAIL_TABLE_COLUMN: 'MAIL_TABLE_COLUMN',
    CLOUD_TABLE_COLUMN: 'CLOUD_TABLE_COLUMN',
    MAIL_MESSAGE: 'MAIL_MESSAGE',
    MAIL_CUSTOM_FOLDER: 'MAIL_CUSTOM_FOLDER',
} as const;

export type DndItemType = (typeof DND_ITEM)[keyof typeof DND_ITEM];
